### ISSUE TITLE
Login / Registration URL Not found

### ISSUE THREAD

**Issue by spiliti** [a2i-dpg/ekShop#5]
I have setup  ekShop for testing and development on a Windows laptop.  when I try to login or register , I get the following message:
**The requested URL was not found on this server**.

 I am using the following environment: 
Apache/2.4.56 (Win64) OpenSSL/1.1.1t PHP/8.2.4 Server at localhost Port 80

**Comment by Nirjhor3029** [comment]
Login-url: ekshop-dpg.test/users/login
Registration-url: ekshop-dpg.test/users/registration

They are working perfectly.

Don't use public directory as root url.

**Comment by spiliti** [comment]
I do not get it. I followed the instructions in the repo for a windows installation (on xampp).  I   am using the following URL:

http://localhost/ekshop

What do you mean "Don't use public directory as root url." which root url?
and the following default Users
#Login as an Admin Username: [admin@admin.com](mailto:admin@admin.com) Password: 123456

#Login as a Customer Username: [customer@example.com](mailto:customer@example.com) Password: 123456

#Login as a Seller Username: [seller@example.com](mailto:seller@example.com) Password: 123456

**Comment by spiliti** [comment]
Thanks.  Now it works
